name: Update README on Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get tag version
        id: tag
        run: |
          # e.g. refs/tags/v1.2.3 -> v1.2.3
          TAG_REF="${GITHUB_REF#refs/tags/}"
          echo "version=$TAG_REF" >> "$GITHUB_OUTPUT"

      - name: Update README version
        run: |
          VERSION="${{ steps.tag.outputs.version }}"
          echo "Updating README to version ${VERSION}"
          tmp=$(mktemp)
          # replace between markers
          sed -E "s|<!--VERSION_START-->.*<!--VERSION_END-->|<!--VERSION_START-->${VERSION}<!--VERSION_END-->|" README.md > "$tmp"
          mv "$tmp" README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "docs(README): update version to ${{ steps.tag.outputs.version }}" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push
